### ISSUE TITLE
Need a .desktop file

### ISSUE THREAD

**Issue by Riptils** [nuIIpointerexception/vterm#1]
Hello, I love your project ! 
Im working on a PKGBUILD for arch users and I wonder if you could just put a .desktop file in extra/linux/ like it (for example) : 
[Desktop Entry]
Name=VTerm
Comment=Cross-platform Vulkan terminal emulator
Exec=vterm
Icon=utilities-terminal
Terminal=false
Type=Application
Categories=Utility;TerminalEmulator;

Thank you for your project !

Edit : this is the link where you can find AUR vterm-git : https://aur.archlinux.org/packages/vterm-git

**Comment by nuIIpointerexception** [comment]
Alright, thanks!
I've just made a commit with a .desktop file in the assets/linux folder.
Let's just see where this project goes :)
