### ISSUE TITLE
crash at launch with the binaries

### ISSUE THREAD

**Issue by Riptils** [nuIIpointerexception/vterm#3]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I launch vterm(without just/cargo run) I have this error message : 
`➜ vterm       
[1]    197596 illegal hardware instruction (core dumped)  vterm`

I just post it in case it helps.

P.S. : the package was compiled with just build (and a just test after).-> from AUR source

### Environment

Archlinux
latest commit (bbf8e18767042fb0efc32ff530fef6de89c7a56c)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[A picture](https://imgur.com/a/OytAfJ0)

### If applicable, attach any further logs or debug discoveries here.

[rust-gdb logs](https://pastebin.com/1mCEEYwt)

**Comment by sa7dse** [comment]
Same for me, on arch with an AMD gpu.

coredump:
```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `vterm'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000059725008ac06 in ?? ()
[Current thread is 1 (Thread 0x76eb42833c00 (LWP 60640))]
(gdb) bt full
#0  0x000059725008ac06 in ?? ()
No symbol table info available.
#1  0x00007ffe7f042d70 in ?? ()
No symbol table info available.
#2  0x000076eb428d7c75 in _int_malloc (av=0x18, bytes=2) at malloc.c:4483
        p = <optimized out>
        iters = <optimized out>
        nb = <optimized out>
        idx = <optimized out>
        bin = <optimized out>
        victim = <optimized out>
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        tcache_unsorted_count = <optimized out>
        tcache_nb = <optimized out>
        tc_idx = <error reading variable tc_idx (Cannot access memory at address 0xffffffffffffffc3)>
        return_cached = <optimized out>
        __PRETTY_FUNCTION__ = "_int_malloc"
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by nuIIpointerexception** [comment]
Okay so currently it's not portable yet because it needs the rust.png from the assets folder.
If you clone the repo and cd in to the vterm folder and then run the vterm executable from /usr/bin it works, because the working directory has the /assets/rust.png file.

I'll fix it soon and add a temporary texture if not found.

**Comment by nuIIpointerexception** [comment]
Okay, so the project has been updated to not use just anymore but instead include a simple Makefile for now and also include a directory "scripts" which has a small script to copy the files to the right directory to run this version.

This should suffice until im done with the first version that should be very feature complete on archlinux.
Also if you want to debug i added a better argument to enable logging, both in release and debug versions for now.

enable logging: --log
set log-level: --log-level=(Trace/Warn/Info/Error/Debug)

Also image loading has now a error if the image is not found.
